server {
    listen 80;
    server_name localhost;

    location / {
        # Esta es la ruta dentro del contenedor donde copiaremos los archivos de Vite
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # MAGIA PARA REACT/VITE: Si alguien recarga la página en una ruta específica (ej: /#/inventory), 
        # Nginx no buscará una carpeta, sino que redirigirá al index.html para que React maneje la ruta.
        try_files $uri $uri/ /index.html;
    }
}